# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.stepGlobal <- function(data, pastInfo, threshold, quantiles) {
    .Call(`_NUNC_NUNCstepGlobal`, data, pastInfo, threshold, quantiles)
}

.stepLocal <- function(data, pastInfo, threshold, quantiles, grid) {
    .Call(`_NUNC_NUNCstepLocal`, data, pastInfo, threshold, quantiles, grid)
}

.NUNCGlobal <- function(dataGen, w, beta, K) {
    .Call(`_NUNC_NUNCGlobal`, dataGen, w, beta, K)
}

.NUNCLocal <- function(dataGen, w, beta, K, grid) {
    .Call(`_NUNC_NUNCLocal`, dataGen, w, beta, K, grid)
}

.NUNCsemiParam <- function(dataGen, w, beta, quantiles) {
    .Call(`_NUNC_NUNCSemiParametric`, dataGen, w, beta, quantiles)
}

.NUNCGlobalOffline <- function(data, w, beta, K) {
    .Call(`_NUNC_NUNCGlobalOffline`, data, w, beta, K)
}

.NUNCLocalOffline <- function(data, w, beta, K, grid) {
    .Call(`_NUNC_NUNCLocalOffline`, data, w, beta, K, grid)
}

.NUNCsemiParamOffline <- function(data, w, beta, quantiles) {
    .Call(`_NUNC_NUNCsemiParametricOffline`, data, w, beta, quantiles)
}

